import { describe, expect, it } from 'vitest';
import { inflateSync } from 'node:zlib';
import {
  renderTaxReceiptPdfAttachment,
  TAX_RECEIPT_PDF_TEMPLATE_VERSION,
} from '../../functions/src/shared/taxReceiptPdf';

function pdfPageCount(pdf: Buffer): number {
  // Page objects are emitted uncompressed (useObjectStreams: false), so the
  // page tree leaves can be counted directly. `/Type /Pages` is the tree node
  // and must be excluded.
  const raw = pdf.toString('latin1');
  return [...raw.matchAll(/\/Type\s*\/Page(?![s])/g)].length;
}

function inflatedPdfText(pdf: Buffer): string {
  const raw = pdf.toString('latin1');
  const streams = [...raw.matchAll(/stream\r?\n([\s\S]*?)\r?\nendstream/g)];
  const inflated = streams
    .map((match) => Buffer.from(match[1], 'latin1'))
    .map((stream) => inflateSync(stream).toString('latin1'))
    .join('\n');
  return [...inflated.matchAll(/<([0-9A-F]+)> Tj/g)]
    .map((match) => Buffer.from(match[1], 'hex').toString('latin1'))
    .join('\n');
}

describe('tax receipt PDF rendering', () => {
  it('renders an official tax receipt PDF attachment', async () => {
    const attachment = await renderTaxReceiptPdfAttachment({
      receiptId: 'giving-tax-1',
      donorName: 'Mira Petrovic',
      donorAddress: '10 Donor Street, Chicago, IL 60601, US',
      churchName: 'St. Sava',
      organizationName: 'St. Sava Orthodox Church',
      organizationAddress: '123 Church Street, Phoenix, AZ',
      taxId: '12-3456789',
      formattedAmount: '$250.00',
      eligibleAmount: '$250.00',
      purpose: 'General Fund',
      receivedDateLabel: 'May 24, 2026',
      issuedDateLabel: 'May 24, 2026',
      receiptNumber: 'STS-2026-000001',
      goodsServicesStatement: 'No goods or services were provided in exchange for this contribution.',
    });

    const pdf = Buffer.from(attachment.content, 'base64');

    expect(attachment.filename).toBe('tax-receipt-STS-2026-000001.pdf');
    expect(attachment.contentType).toBe('application/pdf');
    expect(pdf.subarray(0, 5).toString('utf8')).toBe('%PDF-');
    expect(pdf.length).toBeGreaterThan(1_000);
    const pdfText = inflatedPdfText(pdf);
    expect(pdfText).toContain('Generated by Kandilo.');
    expect(pdfText).toContain(`PDF template version: ${TAX_RECEIPT_PDF_TEMPLATE_VERSION}.`);
    expect(pdfText).not.toContain('Generated from Kandilo receipt record');
    expect(pdfText).not.toContain('giving-tax-1');
  });

  it('renders annual summaries and safely handles non-Latin names', async () => {
    const attachment = await renderTaxReceiptPdfAttachment({
      receiptId: 'annual_abc123',
      donorName: 'Мира Петровић',
      churchName: 'St. Sava',
      organizationName: 'St. Sava Orthodox Church',
      formattedAmount: '$525.00',
      eligibleAmount: '$525.00',
      purpose: 'Annual giving summary',
      receivedDateLabel: 'January 1 - December 31, 2026',
      issuedDateLabel: 'January 15, 2027',
      receiptNumber: 'STS/2026/000009',
      goodsServicesStatement:
        'No goods or services were provided in exchange for this contribution.',
      coveredPeriodLabel: 'January 1 - December 31, 2026',
      contributionCount: 7,
      contributions: [
        {
          dateLabel: 'January 5, 2026',
          purpose: 'Candles',
          amount: '$25.00',
          eligibleAmount: '$25.00',
        },
        {
          dateLabel: 'May 24, 2026',
          purpose: 'General Fund',
          amount: '$500.00',
          eligibleAmount: '$500.00',
        },
      ],
      annualSummaryNote: 'Do not claim both individual and annual receipts for the same gifts.',
    });

    const pdf = Buffer.from(attachment.content, 'base64');
    const pdfText = inflatedPdfText(pdf);

    expect(attachment.filename).toBe('tax-receipt-STS-2026-000009.pdf');
    expect(pdf.subarray(0, 5).toString('utf8')).toBe('%PDF-');
    expect(pdf.length).toBeGreaterThan(20_000);
    expect(pdfText).not.toContain('????');
    expect(pdfText).not.toContain('annual_abc123');
    expect(pdfText).toContain('Contribution Detail');
    expect(pdfText).toContain('January 5, 2026');
    expect(pdfText).toContain('Candles');
  });

  it('does not expose internal receipt ids when the public receipt number is missing', async () => {
    const attachment = await renderTaxReceiptPdfAttachment({
      receiptId: 'annual_private_internal_123',
      donorName: 'Mira Petrovic',
      churchName: 'St. Sava',
      organizationName: 'St. Sava Orthodox Church',
      formattedAmount: '$525.00',
      eligibleAmount: '$525.00',
      purpose: 'Annual giving summary',
      receivedDateLabel: 'January 1 - December 31, 2026',
      issuedDateLabel: 'January 15, 2027',
      receiptNumber: '',
      goodsServicesStatement:
        'No goods or services were provided in exchange for this contribution.',
    });

    const pdfText = inflatedPdfText(Buffer.from(attachment.content, 'base64'));

    expect(attachment.filename).toBe('tax-receipt-unassigned.pdf');
    expect(pdfText).toContain('unassigned');
    expect(pdfText).toContain('Generated by Kandilo.');
    expect(pdfText).not.toContain('annual_private_internal_123');
    expect(pdfText).not.toContain('Generated from Kandilo receipt record');
  });

  it('labels corrected receipts with original and refunded amounts', async () => {
    const attachment = await renderTaxReceiptPdfAttachment({
      receiptId: 'correction_abc123',
      donorName: 'Mira Petrovic',
      churchName: 'St. Sava',
      organizationName: 'St. Sava Orthodox Church',
      formattedAmount: '$75.00',
      eligibleAmount: '$75.00',
      originalAmount: '$100.00',
      refundedAmount: '$25.00',
      purpose: 'General Fund',
      receivedDateLabel: 'May 24, 2026',
      issuedDateLabel: 'May 25, 2026',
      receiptNumber: 'STS-2026-000010',
      goodsServicesStatement:
        'No goods or services were provided in exchange for this contribution.',
      correctionLabel: 'Corrected receipt',
      correctionNote:
        'This corrected receipt replaces a prior receipt after a partial refund or adjustment.',
    });

    const pdf = Buffer.from(attachment.content, 'base64');
    const pdfText = inflatedPdfText(pdf);

    expect(pdfText).toContain('Receipt Type');
    expect(pdfText).toContain('Corrected receipt');
    expect(pdfText).toContain('Original Amount');
    expect(pdfText).toContain('$100.00');
    expect(pdfText).toContain('Refunded Amount');
    expect(pdfText).toContain('$25.00');
    expect(pdfText).toContain('Correction Note');
  });

  it('paginates long detail fields onto additional pages instead of overrunning the footer', async () => {
    const longAddress = Array.from({ length: 24 }, (_, index) =>
      `Suite ${index + 1}, ${index + 100} Very Long Parish Donor Mailing Street Name`
    ).join(', ');
    const longPurpose = 'Restricted building fund for the new parish hall, '.repeat(6);
    const longStatement =
      'No goods or services were provided in exchange for this contribution other than intangible religious benefits. '.repeat(5);

    const attachment = await renderTaxReceiptPdfAttachment({
      receiptId: 'giving-tax-long-1',
      donorName: 'Mira Petrovic',
      donorAddress: longAddress,
      churchName: 'St. Sava',
      organizationName: 'St. Sava Orthodox Church',
      organizationAddress: '123 Church Street, Phoenix, AZ',
      taxId: '12-3456789',
      formattedAmount: '$250.00',
      eligibleAmount: '$250.00',
      purpose: longPurpose,
      receivedDateLabel: 'May 24, 2026',
      issuedDateLabel: 'May 24, 2026',
      receiptNumber: 'STS-2026-000012',
      goodsServicesStatement: longStatement,
    });

    const pdf = Buffer.from(attachment.content, 'base64');
    expect(pdfPageCount(pdf)).toBeGreaterThanOrEqual(2);

    const pdfText = inflatedPdfText(pdf);
    expect(pdfText).toContain('Generated by Kandilo.');
    expect(pdfText).not.toContain('giving-tax-long-1');
  });

  it('renders staged Canada CRA receipt fields when a signed delivery flow is added later', async () => {
    const attachment = await renderTaxReceiptPdfAttachment({
      receiptId: 'cra-staged-1',
      jurisdiction: 'CA',
      donorName: 'Mira Petrovic',
      donorAddress: '10 Donor Street, Edmonton, AB T5J 0N3, CA',
      churchName: 'St. Sava',
      organizationName: 'St. Sava Serbian Orthodox Church',
      organizationAddress: '123 Church Street, Edmonton, AB',
      taxId: '12345 6789 RR0001',
      formattedAmount: '$250.00',
      eligibleAmount: '$250.00',
      purpose: 'General Fund',
      receivedDateLabel: 'May 24, 2026',
      issuedDateLabel: 'May 24, 2026',
      receiptNumber: 'STS-2026-000011',
      goodsServicesStatement: 'No advantage was provided.',
      receiptIssueLocation: 'Edmonton, Alberta',
      authorizedSignerName: 'Fr. Sava',
      authorizedSignerTitle: 'Parish Priest',
    });

    const pdfText = inflatedPdfText(Buffer.from(attachment.content, 'base64'));

    expect(pdfText).toContain('CRA RECEIPT STAGING DRAFT');
    expect(pdfText).toContain('NOT VALID FOR INCOME TAX PURPOSES');
    expect(pdfText).toContain('Charity registration number: 12345 6789 RR0001');
    expect(pdfText).toContain('Canada Revenue Agency: canada.ca/charities-giving');
    expect(pdfText).toContain('Issued Location');
    expect(pdfText).toContain('Edmonton, Alberta');
    expect(pdfText).toContain('Authorized Signer');
    expect(pdfText).toContain('Fr. Sava, Parish Priest');
    expect(pdfText).toContain('Advantage');
    expect(pdfText).toContain('No advantage was provided.');
  });
});
